---
- hosts: ["cassandra-db"]
  user: vagrant
  become: yes
  
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    
  tasks:
  - include: tasks/dependencies.yml
  - include: tasks/repositories.yml
  - include: tasks/java-install.yml
  - include: tasks/cassandra-install.yml
  - include: tasks/start-cassandra.yml
