- name: adding oracle java repository
  apt_repository: repo='ppa:webupd8team/java' state=present
  register: java
  until: java|success
  retries: 5
  delay: 5

- name: add cassandra repo keys
  apt_key:
    url: "https://www.apache.org/dist/cassandra/KEYS"
    state: present
 
- name: add cassandra repo keys, step2
  apt_key:
    keyserver: pool.sks-keyservers.net
    id: A278B781FE4B2BDA

- name: add cassandra repo
  apt_repository:
    repo: deb http://www.apache.org/dist/cassandra/debian 39x main
    state: present

- name: updating machine
  apt: update_cache=yes
