- name: adding oracle java repository
  apt_repository: repo='ppa:webupd8team/java' state=present validate_certs=False

- name: adding dse repo
  shell: echo "deb http://datastaxrepo_gmail.com:utJVKEg4lKeaWTX@debian.datastax.com/enterprise stable main" | sudo tee -a /etc/apt/sources.list.d/datastax.sources.list

- name: adding repo key
  apt_key: url=https://debian.datastax.com/debian/repo_key state=present validate_certs=no

- name: updating machine
  apt: update_cache=yes
